name: aoc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - ipykernel
      - ipywidgets
      - numpy
      - pandas
      - git+https://github.com/fergusch/advent-cli.git
variables:
  ADVENT_PRIV_BOARDS: 2706508
